/** @typedef {'AUTH_SECRET' | 'CITED_BOOTSTRAP_TOKEN' | 'DATABASE_PASSWORD' | 'DATABASE_MIGRATION_PASSWORD' | 'SLACK_WEBHOOK_ENCRYPTION_KEY' | 'MONITORING_CRON_SECRET' | 'NOTIFICATIONS_CRON_SECRET' | 'SMTP_PASSWORD'} SecretFileName */

export {};
